spring.datasource.url=jdbc:mysql://localhost:3306/picpay_challenge
spring.datasource.username=root
spring.datasource.password=MapoftheSoul7Bangtan
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:scripts/users.sql,classpath:scripts/wallets.sql
spring.sql.init.mode=always
application.timezone=America/Sao_Paulo

jwt.secret.key=SSOG54WK!OFM989@Z